import { Flex } from '@chakra-ui/react'
import Head from 'next/head'
import Home from '../components/home';

export default function Index() {
  return (
    <div>
      <Head>
        <title>Highlightify: Text highlight on image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>
        <Home />
      </Flex>
    </div>
  )
}
